version: "3"
services:
  mysql-standalone:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=sa
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  docker-springboot-example:
    image: docker-springboot-example:latest
    ports:
      - 8086:8086
    restart: unless-stopped
    build:
      context: ./
      dockerfile: DOCKERFILE
    depends_on:
      - mysql-standalone