insert into customer(customer_name) values('himanshu');
insert into customer(customer_name) values('vivek');
insert into customer(customer_name) values('ashish');
insert into customer(customer_name) values('garvit');
insert into customer(customer_name) values('basudev');
insert into customer(customer_name) values('naman');
insert into customer(customer_name) values('chintan');
insert into customer(customer_name) values('mayank');
insert into customer(customer_name) values('rishabh');
insert into customer(customer_name) values('karun');

insert into account(balance, customer_id) values(1000, 1);
insert into account(balance, customer_id) values(1000, 2);
insert into account(balance, customer_id) values(1000, 3);
insert into account(balance, customer_id) values(1000, 4);
insert into account(balance, customer_id) values(1000, 5);
insert into account(balance, customer_id) values(1000, 6);
insert into account(balance, customer_id) values(1000, 7);
insert into account(balance, customer_id) values(1000, 8);
insert into account(balance, customer_id) values(1000, 9);
insert into account(balance, customer_id) values(1000, 10);
